CREATE TABLE BOOK_DB(
BOOKNO VARCHAR2(10) PRIMARY KEY,
BOOK VARCHAR2(20),
WRITER VARCHAR2(15),
SITE VARCHAR2(3),
PUBLE VARCHAR2(10));

CREATE SEQUENCE BOOKNO_SEQ
INCREMENT BY 1
START WITH 100; 

INSERT INTO BOOK_DB (BOOKNO, BOOK, WRITER, SITE, PUBLE)
VALUES (BOOKNO_SEQ.NEXTVAL,?,?,?,?);

SELECT * FROM BOOK_DB ORDER BY BOOKNO;

SELECT * FROM BOOK_DB WHERE BOOK =?;

UPDATE BOOK_DB SET WRITER = ?, SITE =?, PUBLE =? WHERE BOOK =?;

DELETE FROM BOOK_DB WHERE BOOK =?;
--------------------------------------------------------
