CREATE TABLE LIBRARY_DB (
BORROW_NO VARCHAR2(6) PRIMARY KEY,
BOOKNAME VARCHAR2(20),
NAME VARCHAR2(6), ADDR VARCHAR2(20),
PHONE NUMBER(14), BORROW_DATE VARCHAR2(20),
RETURN_DATE VARCHAR2(20), BORROW_STATE VARCHAR2(5));

CREATE SEQUENCE LIBRARY_SEQ
INCREMENT BY 1
START WITH 1; 

INSERT INTO LIBRARY_DB 
(BORROW_NO,BOOKNAME, NAME, ADDR, PHONE, BORROW_DATE, RETURN_DATE,BORROW_STATE )
VALUES(LIBRARY_SEQ.NEXTVAL,?,?,?,?,?,?,?);

UPDATE LIBRARY_DB SET RETURN_DATE = ?,BORROW_STATE = ? WHERE BOOKNAME =?;

SELECT * FROM LIBRARY_DB ORDER BY BORROW_NO;
-----------------------------------------------------------------------------
